# trunk branch build definition

trigger:
- trunk

variables:
  containerRegistry: 'containerregistryprod.azurecr.io'
  imageName: '$(containerRegistry)/hes-events-response-api:$(Build.BuildNumber)'

stages:
- stage: Build
  jobs:
    - job: BuildTest
      pool:
        vmImage: 'windows-latest'
      steps:
      - task: SonarCloudPrepare@1
        inputs:
          SonarCloud: 'sonarcloud'
          organization: hafslundnett
          scannerMode: 'MSBuild'
          projectKey: 'hes-events-response-api'
          projectName: 'hes-events-response-api'
      - task: DotNetCoreCLI@2
        displayName: 'dotnet build'
        inputs:
          command: build
  
      - task: DotNetCoreCLI@2
        displayName: 'dotnet test'
        inputs:
          command: test
          projects: |
            **/*Tests/*.csproj
            !**/*IntegrationTests/*.csproj
          arguments: '--configuration $(buildConfiguration) --collect:"Code Coverage"'
          nobuild: true
      - task: SonarCloudAnalyze@1
      - task: SonarCloudPublish@1
        inputs:
          pollingTimeoutSec: '300'

    - job: BuildDockerImage
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      - task: Docker@2
        displayName: 'Docker build image'
        inputs:
          containerRegistry: HafslundNettRegistry
          repository: 'hes-events-response-api'
          command: build
          Dockerfile: '**/Dockerfile'
          tags: '$(Build.BuildNumber)'
      - task: Docker@2
        displayName: 'Login for HafslundNettRegistry'
        inputs:
          containerRegistry: HafslundNettRegistry
          command: login
      - task: aquasecScanner@4
        displayName: 'Scan docker image with AquaSec'
        inputs:
          image: 'containerregistryprod.azurecr.io/hes-response-response-api:$(Build.BuildNumber)'
          scanner: 'containerregistryprod.azurecr.io/aquasec/scanner:latest'
          connection: 'aqua-scanner'
          policies: Default
      - task: Docker@2
        displayName: 'Push docker image'
        inputs:
          containerRegistry: HafslundNettRegistry
          repository: 'hes-events-response-api'
          command: push
          tags: '$(Build.BuildNumber)'

- stage: DeployDev
  jobs:
  - deployment: Deploy
    displayName: deploy hes-events-response-api
    environment: 'Dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: KubernetesManifest@0
            displayName: createSecret
            inputs:
              action: createSecret
              kubernetesServiceConnection: 'HafslundNettDev'
              namespace: hes-extensions
              secretName: containerregistryprodsecret
              dockerRegistryEndpoint: HafslundNettRegistry
          - task: KubernetesManifest@0
            inputs:
              action: 'deploy'
              kubernetesServiceConnection: 'HafslundNettDev'
              namespace: 'hes-extensions'
              manifests: |
                $(System.DefaultWorkingDirectory)/CI/hes-events-response-api.yaml
                $(System.DefaultWorkingDirectory)/CI/ingress.dev.yaml
              containers: 'containerregistryprod.azurecr.io/hes-events-response-api:$(Build.BuildNumber)'
              imagePullSecrets: 'containerregistryprodsecret'

- stage: DeployFuncTest
  jobs:
  - deployment: Deploy
    displayName: deploy hes-events-response-api
    environment: 'FuncTest'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: KubernetesManifest@0
            displayName: createSecret
            inputs:
              action: createSecret
              kubernetesServiceConnection: 'HafslundNettFunctest'
              namespace: 'hes-extensions'
              secretName: containerregistryprodsecret
              dockerRegistryEndpoint: HafslundNettRegistry
          - task: KubernetesManifest@0
            inputs:
              action: 'deploy'
              kubernetesServiceConnection: 'HafslundNettFunctest'
              namespace: 'hes-extensions'
              manifests: |
                $(System.DefaultWorkingDirectory)/CI/hes-events-response-api.yaml
                $(System.DefaultWorkingDirectory)/CI/ingress.functest.yaml
              containers: 'containerregistryprod.azurecr.io/hes-events-response-api:$(Build.BuildNumber)'
              imagePullSecrets: 'containerregistryprodsecret'