# Azure Pipelines configuration
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines

trigger:
- trunk

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  testProject: 'EventsResponseApi.Tests/*.csproj'
  containerregistry: 'containerregistryprod.azurecr.io'
  eventsResponseApiImageName: '$(containerregistry)/hes-events-response-api:$(Build.BuildNumber)'

steps:
# Restore, build and test .NET Core test project
- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore
    projects: $(testProject)

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: build
    projects: $(testProject)
    arguments: '--no-restore'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: test
    projects: $(testProject)
    arguments: '--no-build --filter Category!=Integration'

# Build Docker containers
- task: Docker@1
  displayName: 'Build image hes-events-response-api'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: HafslundNettRegistry
    useDefaultContext: false
    buildContext: .
    dockerFile: EventsResponseApi/Dockerfile
    imageName: '$(eventsResponseApiImageName)'

- bash: 'sed -i "s/:imagetag/:$(Build.BuildNumber)/" *.yaml'
  displayName: 'Replace imagetag with build number in k8s deployments'
  workingDirectory: CI

# Push Docker containers and publish artifacts
# Should only be done on builds from trunk-branch
- task: Docker@1
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/trunk')
  displayName: 'Push image hes-events-response-api'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: HafslundNettRegistry
    command: 'Push an image'
    imageName: '$(eventsResponseApiImageName)'

- task: PublishBuildArtifacts@1
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/trunk')
  displayName: 'Publish kubernetes configuration artifacts'
  inputs:
    PathtoPublish: CI
    ArtifactName: CI

- stage: DeployDev
  jobs:
  - deployment: Deploy
    displayName: deploy hes-events-response-api
    environment: 'Dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: KubernetesManifest@0
            displayName: createSecret
            inputs:
              action: createSecret
              kubernetesServiceConnection: 'HafslundNettDev'
              namespace: hes-extensions
              secretName: containerregistryprodsecret
              dockerRegistryEndpoint: HafslundNettRegistry
          - task: KubernetesManifest@0
            inputs:
              action: 'deploy'
              kubernetesServiceConnection: 'HafslundNettDev'
              namespace: 'hes-extensions'
              manifests: |
                $(System.DefaultWorkingDirectory)/CI/hes-events-response-api.yaml
                $(System.DefaultWorkingDirectory)/CI/ingress.dev.yaml
              containers: 'containerregistryprod.azurecr.io/hes-events-response-api:$(Build.BuildNumber)'
              imagePullSecrets: 'containerregistryprodsecret'

- stage: DeployFuncTest
  jobs:
  - deployment: Deploy
    displayName: deploy hes-events-response-api
    environment: 'FuncTest'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: KubernetesManifest@0
            displayName: createSecret
            inputs:
              action: createSecret
              kubernetesServiceConnection: 'HafslundNettFunctest'
              namespace: hes-extensions
              secretName: containerregistryprodsecret
              dockerRegistryEndpoint: HafslundNettRegistry
          - task: KubernetesManifest@0
            inputs:
              action: 'deploy'
              kubernetesServiceConnection: 'HafslundNettFunctest'
              namespace: 'hes-extensions'
              manifests: |
                $(System.DefaultWorkingDirectory)/CI/hes-events-response-api.yaml
                $(System.DefaultWorkingDirectory)/CI/ingress.functest.yaml
              containers: 'containerregistryprod.azurecr.io/hes-events-response-api:$(Build.BuildNumber)'
              imagePullSecrets: 'containerregistryprodsecret'