
trigger:
  branches:
    exclude:
    - trunk
    - release/*

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  sonarTargetBranchExtraProperty: 'sonar.branch.target=trunk'

steps:
# The UseDotNet steps are only needed as long as agents on Azure DevOps does not support dotnet core 3.1
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.1.x'
# Need dotnet core 2.2 to support sonar cloud
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '2.2.x'
    
- ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
  - bash: echo "##vso[task.setvariable variable=sonarTargetBranchExtraProperty]sonar.pullrequest.base=trunk"
    displayName: 'SonarCloud set sonar.pullrequest.base instead of sonar.branch.target for pull requests (to get correct parent in sonarcloud)'
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonarcloud'
    organization: hafslundnett
    scannerMode: 'MSBuild'
    projectKey: 'hes-events-response-api'
    projectName: 'hes-events-response-api'
    extraProperties: |
      $(sonarTargetBranchExtraProperty)

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: build

- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: test
    projects: |
      **/*Tests/*.csproj
      !**/*IntegrationTests/*.csproj
    arguments: '--configuration $(buildConfiguration) --collect:"Code Coverage"'
    nobuild: true
- task: SonarCloudAnalyze@1
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
- task: sonarcloud-buildbreaker@2
  inputs:
    SonarCloud: 'sonarcloud'
    organization: 'hafslundnett'